version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "changeme"
      POSTGRES_USER: "changeme"
      POSTGRES_PASSWORD: "changeme"
    ports:
      - "5432:5432"

  app:
    build:
      context: src
    stop_signal: SIGKILL
    ports:
      - 5001:5001
    depends_on:
      - postgres
